name: wbc_challenge
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  awesome_icons: ^1.1.0

  # Design 
  google_fonts: ^4.0.3
  lottie: ^2.3.2

  # Monitoring
  catcher: ^0.7.0

  # Tests
  mockito: ^5.4.0

  # System
  build_runner: ^2.3.3
  url_launcher: ^6.1.10
  sqflite: ^2.2.6
  flutter_modular: ^5.0.3
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.2.3
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launch_icon/WBC logo.jpeg"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
     - assets/lottie_animations/
     - assets/
     - assets/launch_icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
